apiVersion: v1
kind: Service
metadata:
  name: docusaurus
  namespace: platform-docs
spec:
  type: NodePort
  selector:
    app: docusaurus
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30505
      protocol: TCP